#!/usr/bin/env bash
# Behavioral regressions for ask-user authority instructions generated by fm-brief.
set -u

# shellcheck source=tests/lib.sh
. "$(dirname "${BASH_SOURCE[0]}")/lib.sh"

BRIEF="$ROOT/bin/fm-brief.sh"
TMP_ROOT=$(fm_test_tmproot fm-ask-user-authority)

test_primary_and_secondmate_instruction_generation() {
  local home ship charter
  home="$TMP_ROOT/home"
  mkdir -p "$home/data"

  FM_HOME="$home" FM_ROOT_OVERRIDE="$ROOT" \
    "$BRIEF" authority-worker sample --mode no-mistakes >/dev/null 2>&1
  ship="$home/data/authority-worker/brief.md"
  assert_grep 'ask-user findings are never yours to answer' "$ship" \
    "generated implementation brief lets the worker own an ask-user decision"
  assert_grep "Firstmate applies the authority contract in its \`AGENTS.md\`" "$ship" \
    "generated implementation brief bypasses the primary authority owner"
  # The procedure is deferred to the crew reference at a named trigger, but the
  # boundary itself stays inline: it fires against the worker's instinct to just
  # answer the question, so it must not depend on the reference having been read.
  assert_grep "Escalate with \`needs-decision:\` and stop" "$ship" \
    "generated implementation brief lost the inline escalate-and-stop action"
  assert_grep "$ROOT/docs/crew-reference.md" "$ship" \
    "generated implementation brief lost the pointer to the deferred pipeline procedure"
  assert_grep "silently bypass firstmate's authority check and any required captain escalation" \
    "$ROOT/docs/crew-reference.md" \
    "the crew reference permits silent ask-user auto-resolution"
  assert_grep "no-mistakes axi respond" "$ROOT/docs/crew-reference.md" \
    "the crew reference lost how an escalated decision returns to the gate"
  assert_no_grep 'the captain, not you, owns the ask-user decisions' "$ship" \
    "generated implementation brief retained conflicting captain-only wording"

  FM_HOME="$home" FM_ROOT_OVERRIDE="$ROOT" FM_SECONDMATE_CHARTER='Handle sample work.' \
    "$BRIEF" authority-mate --secondmate --no-projects >/dev/null 2>&1
  charter="$home/data/authority-mate/brief.md"
  # shellcheck disable=SC2016 # Backticks are literal generated Markdown.
  assert_grep 'The local `AGENTS.md` is your job description' "$charter" \
    "generated secondmate charter does not load the tracked authority boundary"
  assert_no_grep 'continuous frame-by-frame monitoring' "$charter" \
    "generated secondmate charter duplicated the detailed authority procedure"
  pass "primary workers and secondmates receive the authority rule through generated instructions"
}

test_primary_and_secondmate_instruction_generation
